spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
        hbm2ddl:
          auto: update
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always

jwt:
  secret:
    key : 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA